Repository Getple/client, pull requests merged in 2022-04, with the labels that each got.

#5 Feat/3 mainpage routing
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  src/App.tsx
  src/pages/main/index.tsx
Labels: enhancement

#7 Design/6 constant setting
  package-lock.json
  package.json
  src/constant/fontStyle.ts
  src/constant/palette.ts
  src/index.tsx
  src/pages/main/index.tsx
  src/styles/GlobalStyle.tsx
Labels: enhancement

#9 Design #8 GlobalStyle에 Noto-Sans Font 적용
  public/InkLipquidFonts.ttf
  src/styles/GlobalStyle.tsx
  src/styles/fonts/NotoSansKR-Black.otf
  src/styles/fonts/NotoSansKR-Black.woff
  src/styles/fonts/NotoSansKR-Black.woff2
  src/styles/fonts/NotoSansKR-Bold.otf
  src/styles/fonts/NotoSansKR-Bold.woff2
  src/styles/fonts/NotoSansKR-DemiLight.otf
  src/styles/fonts/NotoSansKR-DemiLight.woff
  src/styles/fonts/NotoSansKR-DemiLight.woff2
  src/styles/fonts/NotoSansKR-Light.otf
  src/styles/fonts/NotoSansKR-Light.woff2
  src/styles/fonts/NotoSansKR-Medium.otf
  src/styles/fonts/NotoSansKR-Medium.woff
  src/styles/fonts/NotoSansKR-Medium.woff2
  src/styles/fonts/NotoSansKR-Regular.otf
  src/styles/fonts/NotoSansKR-Regular.woff2
  src/styles/fonts/NotoSansKR-Thin.otf
  src/styles/fonts/NotoSansKR-Thin.woff
  src/styles/fonts/NotoSansKR-Thin.woff2
Labels: design

#10 Feat/2 Search component markup
  package-lock.json
  package.json
  src/components/search.tsx
  src/pages/main/index.tsx
Labels: design

#15 Feat/14 header markup
  package-lock.json
  src/App.tsx
  src/components/header/headerStyle.ts
  src/components/header/index.tsx
  src/constant/fontStyle.ts
  src/pages/main/index.tsx
Labels: enhancement, design

#16 Feat/11 add calendar
  package-lock.json
  package.json
  src/components/search.tsx
  src/components/search/calendar.tsx
  src/components/search/index.tsx
  src/constant/palette.ts
Labels: enhancement, design

#19 Feat/13 login modal
  src/components/header/headerStyle.ts
  src/components/header/index.tsx
  src/components/modal.tsx
  src/constant/palette.ts
  src/styles/GlobalStyle.tsx
Labels: enhancement

#22 feat #18 footer markup
  src/App.tsx
  src/components/footer/FooterStyle.ts
  src/components/footer/index.tsx
  src/components/header/headerStyle.ts
  src/components/header/index.tsx
  src/components/logo.tsx
  src/constant/palette.ts
  src/pages/main/index.tsx
Labels: enhancement, design

#26 Feat/21 count component
  src/components/search/count.tsx
  src/components/search/index.tsx
  src/components/search/searchModal.tsx
  src/components/search/sportsModal.tsx
  src/pages/main/index.tsx
Labels: enhancement, design

#31 Refactor #25 Refactoring Carrousel Component
  src/components/carrousel/card.tsx
  src/components/carrousel/carrouselDirection.tsx
  src/components/carrousel/dummyData/dummyData1.ts
  src/components/carrousel/dummyData/dummyData2.ts
  src/components/carrousel/index.tsx
  src/components/carrousel/styles/cardStyle.ts
  src/components/carrousel/styles/carrouselStyle.ts
  src/components/carrousel/type.ts
  src/components/carrousel/utils.ts
  src/pages/main/index.tsx
Labels: refactor

#30 Feat/24 kakao login
  src/App.tsx
  src/components/header/index.tsx
  src/pages/kakao.tsx
Labels: enhancement

#32 Refactor/25 carrousel refactoring
  src/components/carrousel/index.tsx
  src/components/carrousel/utils.ts
Labels: fix

#34 Refactor/25 carrousel refactoring
  src/components/carrousel/styles/cardStyle.ts
  src/components/carrousel/styles/carrouselStyle.ts
Labels: design

#36 Design #35 메인페이지 전체적인 틀 마크업 작업
  src/pages/main/index.tsx
Labels: design

#37 Design/33 search width
  src/components/search/calendar.tsx
  src/components/search/index.tsx
  src/components/search/searchModal.tsx
Labels: design

#40 Design/38 login modal
  src/components/header/headerStyle.ts
  src/components/header/index.tsx
  src/components/loginModal.tsx
Labels: enhancement

#39 Design #33 change font size in search component
  src/components/search/index.tsx
  src/components/search/searchModal.tsx
Labels: design

#44 Design/43 change search width
  src/components/search/count.tsx
  src/components/search/index.tsx
  src/components/search/sportsModal.tsx
  src/constant/fontStyle.ts
Labels: design

#45 Refactor #25 Carrousel Component Refactoring
  src/components/carrousel/carrouselDirection.tsx
  src/components/carrousel/index.tsx
  src/components/carrousel/styles/cardStyle.ts
  src/components/carrousel/styles/carrouselStyle.ts
  src/components/carrousel/useSlider.ts
  src/components/carrousel/utils.ts
Labels: design, refactor

#48 Feat/47 kakao auth mutaion connect
  .gitignore
  src/index.tsx
  src/pages/kakao.tsx
  src/pages/main/index.tsx
  src/pages/main/mainPresenter.tsx
  src/pages/main/mainStyle.ts
Labels: enhancement, refactor

#55 Feat #51 Add Tag component
  src/components/commons/tag.tsx
Labels: enhancement

#57 Design #52 header 디자인 변경 및 rem 변경
  src/components/header/headerStyle.ts
  src/components/header/index.tsx
Labels: enhancement

#50 Refactor #49 goPrev refactoring and edit copyArray name
  src/components/carrousel/index.tsx
  src/components/carrousel/useSlider.ts
Labels: refactor

#60 Feat/56 select sports type
  public/assets/badminton.png
  public/assets/baseball.png
  public/assets/basketball.png
  public/assets/football.png
  public/assets/futsal.png
  public/assets/golf.png
  public/assets/pingpong.png
  public/assets/tennis.png
  src/components/commons/dropdown.tsx
  src/components/filter/index.tsx
  src/components/filter/sports.tsx
  src/components/search/calendar.tsx
  src/components/search/count.tsx
  src/components/search/index.tsx
  src/components/search/searchModal.tsx
  src/pages/main/mainPresenter.tsx
Labels: enhancement, design

#63 Feat/61 fitlering markup
  src/components/commons/dropdown.tsx
  src/components/commons/tag.tsx
  src/components/filter/index.tsx
  src/pages/main/mainPresenter.tsx
Labels: enhancement, design

#65 feat #61 change sort button color by using state
  src/components/filter/index.tsx
Labels: enhancement

#66 Design/64 FetchList center
  src/components/commons/fetchList/card.tsx
  src/components/commons/fetchList/index.tsx
  src/pages/main/mainPresenter.tsx
Labels: design

#69 design #68 Add responsive layout and delete futsal button
  src/components/commons/dropdown.tsx
  src/components/commons/tag.tsx
  src/components/filter/sports.tsx
Labels: design

#71 Design/67 footer bottom
  src/App.tsx
  src/components/commons/fetchList/card.tsx
  src/components/commons/fetchList/index.tsx
  src/components/header/headerStyle.ts
  src/pages/main/mainStyle.ts
Labels: design

#73 Feat #72 add Presenter-Container
  src/App.tsx
  src/pages/main/index.tsx
  src/pages/main/mainContainer.tsx
  src/pages/main/mainPresenter.tsx
Labels: enhancement

#76 #75 Like component implement
  src/components/commons/like.tsx
Labels: enhancement, design

#77 Feat/74 add post markup
  src/App.tsx
  src/pages/postForm/index.tsx
  src/pages/postForm/postFormContainer.tsx
  src/pages/postForm/postFormPresenter.tsx
  src/pages/postForm/postFormStyle.ts
Labels: enhancement

#79 Feat #78 submit post
  src/pages/postForm/postFormContainer.tsx
  src/pages/postForm/postFormPresenter.tsx
Labels: enhancement

#80 #70 change props name
  src/components/commons/like.tsx
Labels: fix

#81 #70 detail page implement
  src/App.tsx
  src/pages/detail/detailContainer.tsx
  src/pages/detail/detailPresenter.tsx
  src/pages/detail/detailStyle.ts
  src/pages/detail/index.tsx
Labels: enhancement, design

#82 feat #70 add edit button and modify comment
  src/components/commons/tag.tsx
  src/pages/detail/detailContainer.tsx
  src/pages/detail/detailPresenter.tsx
  src/pages/detail/detailStyle.ts
Labels: enhancement
